Attribute VB_Name = "ModExport"
'===============================================================================
' ModExport — Finalization and Report Export
'
' Exports reconciliation results, generates summary reports,
' and handles month-end finalization.
'===============================================================================

Option Explicit

' ---------------------------------------------------------------------------
' Export Reconciliation Summary Report
' ---------------------------------------------------------------------------

Public Sub ExportReconciliationReport(Optional ByVal outputPath As String = "")
    ' Generate and export a reconciliation summary report.

    If outputPath = "" Then
        Dim defaultName As String
        defaultName = "Reconciliation_" & ModConfig.LocationCode() & "_" & _
                      Format(Date, "YYYY_MM") & ".csv"
        outputPath = Application.GetSaveAsFilename( _
            InitialFileName:=defaultName, _
            FileFilter:="CSV Files (*.csv),*.csv", _
            Title:="Save Reconciliation Report")
        If outputPath = "False" Or outputPath = "" Then Exit Sub
    End If

    Dim fileNum As Integer
    fileNum = FreeFile
    Open outputPath For Output As #fileNum

    ' Header section
    Print #fileNum, "ABR RECONCILIATION REPORT"
    Print #fileNum, "Location:," & ModConfig.LocationName()
    Print #fileNum, "Period:," & ModConfig.GetConfigValue("CurrentMonth")
    Print #fileNum, "Generated:," & Format(Now, "MM/DD/YYYY HH:MM:SS")
    Print #fileNum, "Generated By:," & ModHelpers.GetCurrentUserName()
    Print #fileNum, ""

    ' Summary statistics
    Dim wsBank As Worksheet, wsDMS As Worksheet
    Dim wsRecon As Worksheet, wsStaged As Worksheet
    Set wsBank = ThisWorkbook.Sheets("BankData")
    Set wsDMS = ThisWorkbook.Sheets("DMSData")
    Set wsRecon = ThisWorkbook.Sheets("Reconciled")
    Set wsStaged = ThisWorkbook.Sheets("StagedMatches")

    Dim totalBank As Long, totalDMS As Long
    totalBank = WorksheetFunction.Max(0, ModHelpers.GetLastRow(wsBank, 1) - 1)
    totalDMS = WorksheetFunction.Max(0, ModHelpers.GetLastRow(wsDMS, 1) - 1)

    Dim reconCount As Long
    reconCount = WorksheetFunction.Max(0, ModHelpers.GetLastRow(wsRecon, 1) - 1)

    Dim stagedCount As Long
    stagedCount = ModStagingManager.GetStagedCount()

    Print #fileNum, "SUMMARY"
    Print #fileNum, "Total Bank Transactions:," & totalBank
    Print #fileNum, "Total DMS Transactions:," & totalDMS
    Print #fileNum, "Reconciled Matches:," & reconCount
    Print #fileNum, "Pending Review:," & stagedCount

    Dim matchedBankCount As Long, matchedDMSCount As Long
    matchedBankCount = 0
    matchedDMSCount = 0

    Dim lastRow As Long, i As Long
    lastRow = ModHelpers.GetLastRow(wsBank, 1)
    For i = 2 To lastRow
        If wsBank.Cells(i, 10).Value = True Then matchedBankCount = matchedBankCount + 1
    Next i

    lastRow = ModHelpers.GetLastRow(wsDMS, 1)
    For i = 2 To lastRow
        If wsDMS.Cells(i, 9).Value = True Then matchedDMSCount = matchedDMSCount + 1
    Next i

    Dim unmatchedBank As Long, unmatchedDMS As Long
    unmatchedBank = totalBank - matchedBankCount
    unmatchedDMS = totalDMS - matchedDMSCount

    Print #fileNum, "Unmatched Bank:," & unmatchedBank
    Print #fileNum, "Unmatched DMS:," & unmatchedDMS

    If (totalBank + totalDMS) > 0 Then
        Dim matchRate As Double
        matchRate = (matchedBankCount + matchedDMSCount) / (totalBank + totalDMS) * 100
        Print #fileNum, "Match Rate:," & Format(matchRate, "0.0") & "%"
    End If

    Print #fileNum, ""

    ' Reconciled details
    Print #fileNum, "RECONCILED MATCHES"
    Print #fileNum, "Match ID,Match Type,Confidence,Bank Date,Bank Description," & _
                    "Bank Amount,DMS Date,DMS Description,DMS Amount,Reconciled By"

    lastRow = ModHelpers.GetLastRow(wsRecon, 1)
    For i = 2 To lastRow
        Print #fileNum, _
            CStr(wsRecon.Cells(i, 1).Value) & "," & _
            CStr(wsRecon.Cells(i, 2).Value) & "," & _
            Format(wsRecon.Cells(i, 3).Value * 100, "0.0") & "%," & _
            Format(wsRecon.Cells(i, 5).Value, "MM/DD/YYYY") & "," & _
            """" & CStr(wsRecon.Cells(i, 6).Value) & """," & _
            Format(wsRecon.Cells(i, 7).Value, "0.00") & "," & _
            Format(wsRecon.Cells(i, 9).Value, "MM/DD/YYYY") & "," & _
            """" & CStr(wsRecon.Cells(i, 10).Value) & """," & _
            Format(wsRecon.Cells(i, 11).Value, "0.00") & "," & _
            CStr(wsRecon.Cells(i, 13).Value)
    Next i

    Print #fileNum, ""

    ' Unmatched items
    Print #fileNum, "UNMATCHED BANK TRANSACTIONS"
    Print #fileNum, "Row ID,Date,Description,Amount,Check Number"
    lastRow = ModHelpers.GetLastRow(wsBank, 1)
    For i = 2 To lastRow
        If wsBank.Cells(i, 10).Value = False Then
            Print #fileNum, _
                CStr(wsBank.Cells(i, 1).Value) & "," & _
                Format(wsBank.Cells(i, 2).Value, "MM/DD/YYYY") & "," & _
                """" & CStr(wsBank.Cells(i, 4).Value) & """," & _
                Format(wsBank.Cells(i, 5).Value, "0.00") & "," & _
                CStr(wsBank.Cells(i, 6).Value)
        End If
    Next i

    Print #fileNum, ""
    Print #fileNum, "UNMATCHED DMS TRANSACTIONS"
    Print #fileNum, "Row ID,Date,Description,Amount,Reference,Type Code"
    lastRow = ModHelpers.GetLastRow(wsDMS, 1)
    For i = 2 To lastRow
        If wsDMS.Cells(i, 9).Value = False Then
            Print #fileNum, _
                CStr(wsDMS.Cells(i, 1).Value) & "," & _
                Format(wsDMS.Cells(i, 2).Value, "MM/DD/YYYY") & "," & _
                """" & CStr(wsDMS.Cells(i, 3).Value) & """," & _
                Format(wsDMS.Cells(i, 5).Value, "0.00") & "," & _
                CStr(wsDMS.Cells(i, 4).Value) & "," & _
                CStr(wsDMS.Cells(i, 6).Value)
        End If
    Next i

    Close #fileNum

    ModAuditTrail.LogExport "RECONCILIATION_REPORT", outputPath
    MsgBox "Reconciliation report exported to:" & vbCrLf & outputPath, _
           vbInformation, "Export Complete"
End Sub

' ---------------------------------------------------------------------------
' Export to CSV for Power BI
' ---------------------------------------------------------------------------

Public Sub ExportForPowerBI(Optional ByVal outputPath As String = "")
    ' Flat CSV export designed for future Power BI integration.

    If outputPath = "" Then
        Dim defaultName As String
        defaultName = "ABR_PowerBI_" & ModConfig.LocationCode() & "_" & _
                      Format(Date, "YYYY_MM") & ".csv"
        outputPath = Application.GetSaveAsFilename( _
            InitialFileName:=defaultName, _
            FileFilter:="CSV Files (*.csv),*.csv", _
            Title:="Save Power BI Export")
        If outputPath = "False" Or outputPath = "" Then Exit Sub
    End If

    Dim fileNum As Integer
    fileNum = FreeFile
    Open outputPath For Output As #fileNum

    Print #fileNum, "Location,Period,MatchID,MatchType,Confidence," & _
                    "BankDate,BankAmount,BankDesc,DMSDate,DMSAmount,DMSDesc," & _
                    "Status,ReconciledBy,ReconciledDate"

    Dim wsRecon As Worksheet
    Set wsRecon = ThisWorkbook.Sheets("Reconciled")

    Dim lastRow As Long
    lastRow = ModHelpers.GetLastRow(wsRecon, 1)

    Dim locName As String
    locName = ModConfig.LocationName()
    Dim period As String
    period = ModConfig.GetConfigValue("CurrentMonth")

    Dim i As Long
    For i = 2 To lastRow
        Print #fileNum, _
            """" & locName & """," & _
            period & "," & _
            CStr(wsRecon.Cells(i, 1).Value) & "," & _
            CStr(wsRecon.Cells(i, 2).Value) & "," & _
            Format(wsRecon.Cells(i, 3).Value * 100, "0.0") & "," & _
            Format(wsRecon.Cells(i, 5).Value, "YYYY-MM-DD") & "," & _
            Format(wsRecon.Cells(i, 7).Value, "0.00") & "," & _
            """" & CStr(wsRecon.Cells(i, 6).Value) & """," & _
            Format(wsRecon.Cells(i, 9).Value, "YYYY-MM-DD") & "," & _
            Format(wsRecon.Cells(i, 11).Value, "0.00") & "," & _
            """" & CStr(wsRecon.Cells(i, 10).Value) & """," & _
            "RECONCILED," & _
            CStr(wsRecon.Cells(i, 13).Value) & "," & _
            Format(wsRecon.Cells(i, 12).Value, "YYYY-MM-DD")
    Next i

    Close #fileNum
    ModAuditTrail.LogExport "POWER_BI", outputPath
End Sub

' ---------------------------------------------------------------------------
' Month-End Finalization
' ---------------------------------------------------------------------------

Public Sub FinalizeMonth()
    ' Finalize the current reconciliation period.
    ' Checks for pending staged matches and prompts user.

    Dim stagedCount As Long
    stagedCount = ModStagingManager.GetStagedCount()

    If stagedCount > 0 Then
        Dim response As VbMsgBoxResult
        response = MsgBox("There are still " & stagedCount & _
                          " staged matches pending review." & vbCrLf & vbCrLf & _
                          "Do you want to finalize anyway?" & vbCrLf & _
                          "(Pending matches will remain for next session)", _
                          vbYesNo + vbExclamation, "Finalize Month")
        If response = vbNo Then Exit Sub
    End If

    ' Export outstanding items
    ModOutstanding.ExportOutstanding

    ' Export reconciliation report
    ModExport.ExportReconciliationReport

    ' Log finalization
    Dim summary As String
    summary = "Month finalized. Reconciled: " & ModStagingManager.GetAcceptedCount() & _
              ", Pending: " & stagedCount
    ModAuditTrail.LogEvent "MONTH_FINALIZED", summary

    MsgBox "Month finalization complete." & vbCrLf & vbCrLf & summary, _
           vbInformation, "Finalization Complete"
End Sub
